open_graph:
  enable: true
  twitter_id: # for open_graph meta

logo:
  icon: /blog/assets/images/avatar.jpg
  title: 黄先森的小屋
  subtitle: '怀热望，赴山海 | Hold hope, chase mountains and seas.'

# 侧边栏主功能导航菜单
menubar:
  columns: 4 # 一行多少个
  items: # 可按照自己需求增加，符合以下格式即可
    - id: post # 页面中高亮的 menu_id
      theme: '#1BCDFC' # 高亮时的颜色，仅 svg 中 fill="currentColor" 时有效
      icon: solar:documents-bold-duotone # 支持 svg/img 标签，可以定义在 icons.yml 文件中，也支持外部图片的 URL
      title: 博客 # 标题
      url: / # 跳转链接，支持相对路径和绝对路径
    - id: wiki
      theme: '#3DC550'
      icon: solar:notebook-bookmark-bold-duotone
      title: 文档
      url: /wiki/
    - id: notes
      theme: '#FA6400'
      icon: solar:planet-bold-duotone
      title: 笔记
      url: /notes/
    - id: social
      theme: '#F44336'
      icon: solar:chat-line-bold-duotone
      title: 关于
      url: /about/

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search:
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    skip_search: [] # 指定 path 中的内容不被搜索。
    codeblock: true # 是否搜索代码块（需要content: true)
# 避免被搜索的页面；如：['about*', 'post/2023*']
skip_search: []
# 页脚 配置一些网址链接
# footer:
#   social:
#     github:
#       icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder/social/08a41b181ce68.svg"/>'
#       url: https://
#     music:
#       icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder/social/3845874.svg"/>'
#       url: https://
#     unsplash:
#       icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder/social/3616429.svg"/>'
#       url: https://
#     comments:
#       icon: '<img src="https://gcore.jsdelivr.net/gh/cdn-x/placeholder/social/942ebbf1a4b91.svg"/>'
#       url: https://

article:
  # 文章类型决定布局风格，有两种风格可选，tech: 默认技术类文章, story: 图文类文章，文字和段落间增距大。
  type: tech # tech/story
  # 许可协议
  license: '本文采用 [署名-非商业性使用-相同方式共享 4.0 国际](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。'
  # 分享链接
  # 分享至微信会生成对应的页面二维码，weibo 和 email 会自动跳转到对应软件或网页，link 会拷贝当前页面链接至剪切板。
  # share: [wechat, weibo, email, link]

# 表情包
tag_plugins:
  emoji:
    default: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/qq/{name}.gif
    twemoji: https://gcore.jsdelivr.net/gh/twitter/twemoji/assets/svg/{name}.svg
    qq: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/qq/{name}.gif
    aru: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/aru-l/{name}.gif
    tieba: https://gcore.jsdelivr.net/gh/cdn-x/emoticons/tieba/{name}.png

# site_tree:
#   home:
#     sidebar: starter, welcome, recent
#   index_blog:
#     sidebar: starter, welcome, recent
#   index_topic:
#     menu_id: topic
#   topic:
#     menu_id: topic

style:
  text-align: justify
  smooth_scroll: false
  codeblock:
    scrollbar: 0px
  font-size:
    body: 1rem
  font-family:
    logo: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    body: '"LXGW WenKai Screen", system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
    code: '"LXGW WenKai Screen", Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
    codeblock: 'Menlo, Monaco, Consolas, system-ui, "Courier New", monospace, sans-serif'
